<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Cpaturing Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="D:\Screenshot\error.png">Screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="DataDrivenSuite" duration-ms="14102" started-at="2018-12-09T11:50:33Z" finished-at="2018-12-09T11:50:48Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="6220" started-at="2018-12-09T11:50:33Z" finished-at="2018-12-09T11:50:40Z">
      <class name="com.w2a.Testcases.Login">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.w2a.Testcases.Login@752325ad]" name="loginAsBankManager" duration-ms="6037" started-at="2018-12-09T11:50:34Z" finished-at="2018-12-09T11:50:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login Failed
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.Testcases.Login.loginAsBankManager(Login.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Cpaturing Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="D:\Screenshot\error.png">Screenshot</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.Testcases.Login -->
    </test> <!-- LoginTest -->
    <test name="AddCustomerTest" duration-ms="7772" started-at="2018-12-09T11:50:40Z" finished-at="2018-12-09T11:50:48Z">
      <class name="com.w2a.Testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.Testcases.AddCustomerTest@4009e306]" name="setUp" is-config="true" duration-ms="21066" started-at="2018-12-09T11:50:12Z" finished-at="2018-12-09T11:50:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="AddCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.Testcases.AddCustomerTest@4009e306]" name="AddCustomerTest" duration-ms="7231" started-at="2018-12-09T11:50:40Z" data-provider="getData" finished-at="2018-12-09T11:50:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Aurora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[700068]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddCustomerTest -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.w2a.Testcases.AddCustomerTest@4009e306]" name="TearDown" is-config="true" duration-ms="789" started-at="2018-12-09T11:50:48Z" finished-at="2018-12-09T11:50:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.w2a.Testcases.AddCustomerTest -->
    </test> <!-- AddCustomerTest -->
  </suite> <!-- DataDrivenSuite -->
</testng-results>
